### ISSUE TITLE
add support for other models

### ISSUE THREAD

**Issue by antpass79** [microsoft/typechat.net#217]
Is there a plan for supporting other models?

currently the library supports gpt 3.5 turbo and gpt 4.

The first model is fast enough, but not so precisly.
In addition, in case of a complex situation, the option that I followed is to have different schemas and make parallel calls, managing the results once they come back.

The second model is more accurate but very very slow.
In addition, in case of a complex situation, it's possible to manage the complexity also with a single schema. The problem is that almost always a timeout occurs (15 seconds not changeable).

Thank you,
Antonio

**Comment by StanislavPrusac** [comment]
+1 - add support for other models: Phi-3, LLAMA, ...
